#!/usr/bin/python

import smtplib
import requests
import json
import datetime
import sys
import os
programDir = os.path.dirname(os.path.abspath(__file__))

# api tokens
weather_api_token = '288eaa3e24928fe1624619297e907e5b'
geoip_api_token = 'access_key=706012c40c1b18043fdcba7c996911bd' # create account at https://darksky.net/dev/



# function to get ip address
def get_ip():
    try:
        ip_url = "http://jsonip.com/"
        req = requests.get(ip_url)
        ip_json = json.loads(req.text)
        return ip_json['ip']
    except Exception as e:
        f.write("Error: %s." %e)
        traceback.print_exc()
        return "Error: %s. Cannot get ip." % e

# get lat and lon location from ip address
def get_loc():
    location_req_url = "http://api.ipstack.com/%s?%s" % (get_ip(), geoip_api_token)
    r = requests.get(location_req_url)
    location_obj = json.loads(r.text)
    lat = location_obj['latitude']
    lon = location_obj['longitude']
    return [lat, lon]


# get weather from latitude and longitude
def get_weather(coord):
    weather_req_url = "https://api.darksky.net/forecast/%s/%s,%s?lang=%s&units=%s" % (weather_api_token, coord[0], coord[1], 'en','us')
    r = requests.get(weather_req_url)
    weather_obj = json.loads(r.text)
    return weather_obj

# parse out relevant forecast
def get_forecast():
    weather = get_weather(get_loc())
    #forecast = get_weather(get_loc())['daily']['data'][0]['summary']
    forecast = get_weather(get_loc())['currently']
    for each in forecast:
        print each
    return forecast

get_forecast()
print(get_forecast())
